### PR TITLE
Adding current required html step to XML build.

### PR DESCRIPTION
**Pull request by mareuter**

### CODE REVIEW

**Comment by avillalobos** [comment]
In line 93 of ts_xml init.pp class, there is an option to run the html as well, so using ts_xml_languages variable, you can send html from hiera (as another language), to compile "HTML". Is the HTML step required by all the subsystems? if so, it make sense to have it there instead of an optional step, but if html is no required by all the subsystems, I think is better to keep it in hiera, and hence use ts_xml_languages variable to send that information into the puppet module. Given that ts_xml_languages is an array, and the order is respected, then we could add html as the first language. In the meanwhile I did a commit to have html step within the module, but is not yet merged into master. Please let me know what do you think.

**Review by avillalobos — COMMENTED** [review]
In line 93 of ts_xml init.pp class, there is an option to run the html as well, so using ts_xml_languages variable, you can send html from hiera (as another language), to compile "HTML". Is the HTML step required by all the subsystems? if so, it make sense to have it there instead of an optional step, but if html is no required by all the subsystems, I think is better to keep it in hiera, and hence use ts_xml_languages variable to send that information into the puppet module. Given that ts_xml_languages is an array, and the order is respected, then we could add html as the first language. In the meanwhile I did a commit to have html step within the module, but is not yet merged into master. Please let me know what do you think.

**Comment by mareuter** [comment]
The HTML step is required by all builds regardless of subsystem, is a known artifact of the build process and is independent of subsequent subsystem language choices. Therefore, this is not a configurable step.

**Comment by avillalobos** [comment]
All changes were already verified, this seems to be good to go.

**Pull request merged**
